# Generated by Django 4.0.5 on 2022-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
